/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -v -a agent_adaptor.h: agent.xml
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef AGENT_ADAPTOR_H_1388479591
#define AGENT_ADAPTOR_H_1388479591

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.bluez.obex.Agent1
 */
class Agent1Adaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.bluez.obex.Agent1")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.bluez.obex.Agent1\">\n"
"    <method name=\"Release\"/>\n"
"    <method name=\"Cancel\"/>\n"
"    <method name=\"AuthorizePush\">\n"
"      <arg direction=\"in\" type=\"o\" name=\"transfer\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"Fullpath\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    Agent1Adaptor(QObject *parent);
    virtual ~Agent1Adaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    QString AuthorizePush(const QDBusObjectPath &transfer);
    void Cancel();
    void Release();
Q_SIGNALS: // SIGNALS
};

#endif
